### ISSUE TITLE
Buffer setting doesn't work

### ISSUE THREAD

**Issue by crobibero** [Threadfin/Threadfin#17]
Version: 0.9 (6)
Host: docker fyb3roptik/threadfin:0.9.4
Attempted with all buffer settings with the same result.

Startup:
```
2022/10/15 14:11:48 [Threadfin] Version:                0.9 Build: 6
2022/10/15 14:11:48 [Threadfin] Database Version:       0.5.0
2022/10/15 14:11:48 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 0
2022/10/15 14:11:48 [Threadfin] Hostname:               6099b2db893d
2022/10/15 14:11:48 [Threadfin] System Folder:          /home/threadfin/conf/
For help run: /home/threadfin/bin/threadfin -h

2022/10/15 14:11:48 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json
2022/10/15 14:11:48 [Threadfin] Temporary Folder:       /tmp/threadfin/2022-10-RRNR-D4IG3G/
2022/10/15 14:11:48 [Threadfin] GitHub:                 https://github.com/Threadfin
2022/10/15 14:11:48 [Threadfin] Git Branch:             Beta [Threadfin]
2022/10/15 14:11:48 [Threadfin] SSDP / DLNA:            true
2022/10/15 14:11:48 BRANCH:  Beta
2022/10/15 14:11:48 FILE:  https://github.com/Threadfin/Threadfin/releases/download/0.9.6/Threadfin_linux_amd64?raw=true
```

Error:
```
2022/10/15 14:13:51 [Threadfin] Buffer:                 true [ffmpeg]
2022/10/15 14:13:51 [Threadfin] Buffer Size:            1024 KB
2022/10/15 14:13:51 [Threadfin] Channel Name:            Travel
2022/10/15 14:13:51 [Threadfin] Client User-Agent:      Jellyfin-Server/10.8.5
2022/10/15 14:13:51 http: panic serving 172.25.0.5:45168: interface conversion: *osfs.OsFS is not avfs.VolumeManager: missing method VolumeAdd
goroutine 170 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:1825 +0xbf
panic({0x82f8a0, 0xc001fa4de0})
        /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:844 +0x258
threadfin/src.checkVFSFolder({0xc01bb0a780, 0x38}, {0xa0b1c0, 0xc0001fc6f0})
        /home/runner/work/Threadfin/Threadfin/src/toolchain.go:63 +0x79
threadfin/src.bufferingStream({0xc007a71c80, 0x14}, {0xc01a85c690, 0x26}, {0x0, 0x0}, {0xc00a624875, 0x7}, {0xa08930, 0xc0003de460}, ...)
        /home/runner/work/Threadfin/Threadfin/src/buffer.go:75 +0x390
threadfin/src.Stream({0xa08930, 0xc0003de460}, 0xc01897a500)
        /home/runner/work/Threadfin/Threadfin/src/webserver.go:183 +0x6ef
net/http.HandlerFunc.ServeHTTP(0x7f08255674d8?, {0xa08930?, 0xc0003de460?}, 0x40efe5?)
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xa08930, 0xc0003de460}, 0xc01897a500)
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc001fa4c00?}, {0xa08930, 0xc0003de460}, 0xc01897a500)
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001345a0, {0xa08ca8, 0xc019b68ea0})
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:3071 +0x4db
```

**Comment by xtinct101** [comment]
Make sure “Store Buffer in Ram” is checked otherwise nothing works.

**Comment by crobibero** [comment]
Yep that fixed it- thanks
