### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by susnick** [Threadfin/Threadfin#171]
**Describe the bug**
Startup crashes with panic: runtime error: index out of range [0] with length 0

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu] Macos Sonoma Version 14.0
- Arch [e.g. Intel 64 Bit] arm64 
- Threadfin Version and Build [to be found in the Threadfin log] Version 1.0 Build 21

iptv channels were deleted from provider
error on Map channels

[Threadfin] [ERROR] Missing EPG data: USA: INVESTIGATION DISCOVERY FHD 1080 () - EC: 0
Threadfin] XEPG:                   Create XMLTV file (/Users/scott/.threadfin/data/threadfin.xml)
panic: runtime error: index out of range [0] with length 0

goroutine 56 [running]:
threadfin/src.createLiveProgram({{0x140098921f8, 0x14}, {0x14004112880, 0x3}, {0x140115ec9c0, 0x35}, {0x14004112884, 0xc}, {0x140041128c0, 0xb}, ...}, ...)
	/home/runner/work/Threadfin/Threadfin/src/xepg.go:952 +0x850
threadfin/src.createDummyProgram({{0x140098921f8, 0x14}, {0x14004112880, 0x3}, {0x140115ec9c0, 0x35}, {0x14004112884, 0xc}, {0x140041128c0, 0xb}, ...})
	/home/runner/work/Threadfin/Threadfin/src/xepg.go:999 +0x84
threadfin/src.getProgramData({{0x140098921f8, 0x14}, {0x14004112880, 0x3}, {0x140115ec9c0, 0x35}, {0x14004112884, 0xc}, {0x140041128c0, 0xb}, ...})
	/home/runner/work/Threadfin/Threadfin/src/xepg.go:843 +0xf0
threadfin/src.createXMLTVFile()
	/home/runner/work/Threadfin/Threadfin/src/xepg.go:814 +0x780
threadfin/src.buildXEPG.func2()
	/home/runner/work/Threadfin/Threadfin/src/xepg.go:115 +0x20
created by threadfin/src.buildXEPG
	/home/runner/work/Threadfin/Threadfin/src/xepg.go:113 +0x1ac

**Comment by susnick** [comment]
just downloaded 1.0.22 and problem is fixed
