### ISSUE TITLE
Enabling caching causes stream to fail

### ISSUE THREAD

**Issue by Wmartin417** [Threadfin/Threadfin#18]
Hi, thanks for all your hard work on this, really liking this so far.

My setup:
Docker version 20.10.18, build b40c2f6 on Debian 11
Threadfin 0.9 (6) on docker its fyb3roptik/threadfin:0.9.4

When I start the stream, I get:

```
2022/10/15 21:31:50 http: panic serving 172.19.0.3:46154: interface conversion: *osfs.OsFS is not avfs.VolumeManager: missing method VolumeAdd
goroutine 457 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:1825 +0xbf
panic({0x82f8a0, 0xc000364750})
        /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:844 +0x258
threadfin/src.checkVFSFolder({0xc012d18840, 0x38}, {0xa0b1c0, 0xc00007fce0})
        /home/runner/work/Threadfin/Threadfin/src/toolchain.go:63 +0x79
threadfin/src.bufferingStream({0xc01260bfb0, 0x14}, {0xc01505e000, 0x2d}, {0x0, 0x0}, {0xc0130e00a8, 0x17}, {0xa08930, 0xc0025e21c0}, ...)
        /home/runner/work/Threadfin/Threadfin/src/buffer.go:75 +0x390
threadfin/src.Stream({0xa08930, 0xc0025e21c0}, 0xc002574200)
        /home/runner/work/Threadfin/Threadfin/src/webserver.go:183 +0x6ef
net/http.HandlerFunc.ServeHTTP(0x7f73ab8311e0?, {0xa08930?, 0xc0025e21c0?}, 0x40efe5?)
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xa08930, 0xc0025e21c0}, 0xc002574200)
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0003645d0?}, {0xa08930, 0xc0025e21c0}, 0xc002574200)
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001e80a0, {0xa08ca8, 0xc000287d10})
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:3071 +0x4db
```

I see osfs.OsFS, I assume FS means filesystem? I am running ZFS on the host with the docker volume on the ZFS volume if that makes any difference.

Once I disable caching, everything streams fine,

if you need anymore info, let me know.

EDIT: should also note I tried this with all three caching methods and they all yielded the same results.

**Comment by xtinct101** [comment]
Same issue as previously noted. You need to enable “Store buffer in RAM” for it to work.

**Comment by Fyb3roptik** [comment]
Ah yeah store buffer in RAM for now. I'll add this as a bug! I also use zfs!

**Comment by Fyb3roptik** [comment]
I set RAM buffer to default to true by default in 0.9.7
