### ISSUE TITLE
Latest release fail to start stream

### ISSUE THREAD

**Issue by Drvolks** [Threadfin/Threadfin#435]
**Describe the bug**
I updated Threadfin to the latest release and I it crashes whenever I start a stream. Rollbacking to docker image `fyb3roptik/threadfin:1.2.10` fixes the issue. The problem starts at version 1.2.11.
```
2024/11/03 14:48:57 [Threadfin] XEPG:                   Create XMLTV file (/home/threadfin/conf/data/threadfin.xml)
2024/11/03 14:48:57 [Threadfin] XEPG:                   Compress XMLTV file (/home/threadfin/conf/data/threadfin.xml.gz)
2024/11/03 14:48:57 [Threadfin] XEPG:                   Create M3U file (/home/threadfin/conf/data/threadfin.m3u)
2024/11/03 14:48:57 [Threadfin] XEPG:                   Ready to use
2024/11/03 14:49:03 http: panic serving <Apple TV IP address>:56694: interface conversion: interface {} is nil, not string
goroutine 12 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x83e020, 0xc0008bc2a0})
	/usr/local/go/src/runtime/panic.go:844 +0x258
threadfin/src.Stream({0x9f6750, 0xc0001200e0}, 0xc000590400)
	/src/src/webserver.go:147 +0x973
net/http.HandlerFunc.ServeHTTP(0x7f530004ff08?, {0x9f6750?, 0xc0001200e0?}, 0x40efe5?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f6750, 0xc0001200e0}, 0xc000590400)
	/usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0008bc0c0?}, {0x9f6750, 0xc0001200e0}, 0xc000590400)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000b0280, {0x9f6af8, 0xc00007ca80})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Server (please complete the following information):**
- OS **Linux + docker**
- Arch **amd64**
- Threadfin Version and Build **> 1.2.11**

**To Reproduce**
1. Start docker container
```
docker run -d \
  --restart unless-stopped \
  --name=threadfin \
 [...]
  fyb3roptik/threadfin
```
2. On AppleTV, start playing an IPTV channel (using iPlayTV app)
3. Stream doesn't start
4. I see the panic error in the logos

**Expected behavior**
Working with version 1.2.10

**Comment by PiratesIRC** [comment]
See #430 
https://github.com/Threadfin/Threadfin/issues/430

**Comment by Drvolks** [comment]
Thanks for pointing this out, I was indeed able to resolve the issue by saving the playlist. At first I tried the update button, but it's really the save button that is fixing the problem.
