### ISSUE TITLE
Panic attempting to stream

### ISSUE THREAD

**Issue by golaat** [Threadfin/Threadfin#471]
**Describe the bug**
v1.2.18 throws the following error when attempting to stream:

```
2024/12/02 20:46:57 http: panic serving 192.168.0.2:57227: interface conversion: interface {} is nil, not string
goroutine 80 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
panic({0xc247e0, 0xc007cf8480})
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
threadfin/src.bufferingStream({0xc006b1dd58, 0x14}, {0xc007a8a380, 0x35}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /home/runner/work/Threadfin/Threadfin/src/buffer.go:183 +0x1ec5
threadfin/src.Stream({0xde8200, 0xc0026f01c0}, 0xc0025d4200)
        /home/runner/work/Threadfin/Threadfin/src/webserver.go:185 +0x938
net/http.HandlerFunc.ServeHTTP(0x183cd0a4448?, {0xde8200?, 0xc0026f01c0?}, 0x7ed7c5?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xde8200, 0xc0026f01c0}, 0xc0025d4200)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc007cf8240?}, {0xde8200, 0xc0026f01c0}, 0xc0025d4200)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00d38a320, {0xde8578, 0xc000596180})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db
```

I was previously running 1.2.5 and it had no issue. Infact, reverting to this version works just fine.

**Comment by joshjryan** [comment]
Open and save your playlists. The buffer has not been saved for your playlist.

**Comment by golaat** [comment]
Yeh, I kind of found that on my own at the same time you posted this :)
