### ISSUE TITLE
Windows:  FFMPEG Buffering:  "No client is using this channel anymore. Streaming Server connection has ended"

### ISSUE THREAD

**Issue by mkanet** [Threadfin/Threadfin#61]
**Issue**
When tuning into an IPTV channel from Plex Android client, intermittently/sometimes I will get the below Plex error.  If I try again, sometimes it works without the error.
![Screenshot 04-06-2023 at 11 38 02 AM](https://user-images.githubusercontent.com/811008/230467317-93d8740b-a1b4-450b-9c5c-86b459dac7cd.png)

**Threadfin log:**
```
2023-04-06 11:32:17 [Threadfin] Buffer:                 true [ffmpeg]
2023-04-06 11:32:17 [Threadfin] Buffer Size:            512 KB
2023-04-06 11:32:17 [Threadfin] Channel Name:           USATV
2023-04-06 11:32:17 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
2023-04-06 11:32:19 [Threadfin] Streaming Status:       Playlist: LiveTV - Tuner: 1 / 3
2023-04-06 11:32:19 [Threadfin] FFMPEG path:            C:\Program Files (x86)\IPTV\ffmpeg.exe
2023-04-06 11:32:19 [Threadfin] Streaming URL:          http://xc-url:80/live/mkanet/blc526wK3W/2503.ts
2023-04-06 11:32:19 [Threadfin] FFMPEG:                 Processing data
2023-04-06 11:32:19 [Threadfin] Streaming Status:       Receive data from FFMPEG
2023-04-06 11:32:21 [Threadfin] Streaming Status:       Buffering data from FFMPEG
2023-04-06 11:32:28 [Threadfin] Streaming Status:       Client has terminated the connection
2023-04-06 11:32:28 [Threadfin] Streaming Status:       Channel: USATV (Clients: 0)
2023-04-06 11:32:29 [Threadfin] Streaming Status:       Channel: USATV - No client is using this channel anymore. Streaming Server connection has ended
2023-04-06 11:32:29 [Threadfin] Streaming Status:       Playlist: LiveTV - Tuner: 0 / 3
```
PS: Sometimes, I will see the below message in the logs when FFMpeg is enabled.  However, I'm not sure if it's related to this issue or not:
```
[h264 @ 000002027c493e80] non-existing SPS 0 referenced in buffering period
```

**Things I've tried:**
- If I increase the buffer size (even up to 3MBs), it doesn't prevent this issue.  
- If I increase the timeout period to even 2500ms, it doesn't prevent this issue.
- Using to different versions of FFmpeg.exe for Windows doesn't prevent this issue.
- RAM buffering is always enabled.
- FFMpeg flags (Threadfin defaults).
- **If I select _No Buffering (Client connects directly to the streaming server)_, streams connect noticeably faster; avoiding this issue in _most_ cases.**

**Plex Android Client settings:**
Quality:                                   [Original bitrate/DirectStream]
Automatically adjust quality:  [Disabled]

- OS:  Win11 (64bit)
- Arch: Intel 64 Bit
- Threadfin Version:  1.0 (7)

This issue appears to be related to FFMpeg buffering.  However, I'm not sure what to change to prevent this issue from happening.  NOTE:  I also had this issue with xteve, if I remember correctly.

**Comment by Fyb3roptik** [comment]
Are there any ffmpeg errors int he log?

**Comment by mkanet** [comment]
> Are there any ffmpeg errors int he log?

HI.  Thank you for the quick response.  No there wasn't.  I posted everything in the log related to this stream.  It seems to think the client is disconnecting it.  This issue doesn't happen from a PC with an internet connection.

Any suggestions?

**Comment by mkanet** [comment]
@Fyb3roptik is there any way to display more detailed information on what's causing this issue?  The current threadfin log doesn't show anything useful to debug this issue.  I really don't know enough about threadfin to figure this out on my own.

**Comment by Fyb3roptik** [comment]
It should show the ffmpeg error

**Comment by mkanet** [comment]
Unfortunately. there is no ffmpeg error.  At least not in threadfin log.  Anyway, I think the problem is not related to ffmpeg.  When I disabled ffmpeg, the log shows that threadfin passes the stream to the plex client.  Then, same thing happens:   **_Client has terminated the connection_**

Very interesting clue:  This issue does NOT happen to Roku Plex client (connected via ethernet).  It also does not happen to Plex (inweb browser). 

Any ideas why the Plex client would _sometimes_ disconnect after threadfin passes the stream?  And, never has issues with Roku/Web browser clients?

**Comment by mkanet** [comment]
@Fyb3roptik I figured out why this issue is happening.  The issue appears to be specific to Plex Android app when handling audio stream/codec (see below log).  The below errors happen every time the issue happens.  Maybe you might know how to prevent this issue?

```
04-08 16:13:04.098  i: [FFmpeg] [WARN] [mpegts @ 0xb400006f2b833400] Could not find codec parameters for stream 1 (Audio: aac (LC) ([15][0][0][0] / 0x000F), 24000 Hz, 0 channels, 96 kb/s): unspecified number of channels
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

04-08 16:13:04.098  i: [FFmpeg] [INFO] Input #0, mpegts, from '':

04-08 16:13:04.099  i: [FFmpeg] [INFO]   Duration: 
04-08 16:13:04.099  i: [FFmpeg] [INFO] N/A
04-08 16:13:04.099  i: [FFmpeg] [INFO] , start: 
04-08 16:13:04.099  i: [FFmpeg] [INFO] 24.726622
04-08 16:13:04.099  i: [FFmpeg] [INFO] , bitrate: 
04-08 16:13:04.099  i: [FFmpeg] [INFO] N/A
04-08 16:13:04.100  i: [FFmpeg] [INFO] 

04-08 16:13:04.100  i: [FFmpeg] [INFO]   Program 1 

04-08 16:13:04.100  i: [FFmpeg] [INFO]     Metadata:

04-08 16:13:04.100  i: [FFmpeg] [INFO]       service_name    : 
04-08 16:13:04.100  i: [FFmpeg] [INFO] Service01
04-08 16:13:04.101  i: [FFmpeg] [INFO] 

04-08 16:13:04.101  i: [FFmpeg] [INFO]       service_provider: 
04-08 16:13:04.101  i: [FFmpeg] [INFO] FFmpeg
04-08 16:13:04.101  i: [FFmpeg] [INFO] 

04-08 16:13:04.101  i: [FFmpeg] [INFO]   Stream #0:0
04-08 16:13:04.101  i: [FFmpeg] [INFO] [0x100]
04-08 16:13:04.102  i: [FFmpeg] [INFO] : Video: h264 (Main) ([27][0][0][0] / 0x001B), none(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions
04-08 16:13:04.102  i: [FFmpeg] [INFO] , 
04-08 16:13:04.102  i: [FFmpeg] [INFO] 59.94 fps, 
04-08 16:13:04.102  i: [FFmpeg] [INFO] 59.94 tbr, 
04-08 16:13:04.102  i: [FFmpeg] [INFO] 90k tbn
04-08 16:13:04.103  i: [FFmpeg] [INFO] 

04-08 16:13:04.106  i: [FFmpeg] [INFO]   Stream #0:1
04-08 16:13:04.107  i: [FFmpeg] [INFO] [0x101]
04-08 16:13:04.107  i: [FFmpeg] [INFO] : Audio: aac (LC) ([15][0][0][0] / 0x000F), 24000 Hz, 0 channels, 96 kb/s
04-08 16:13:04.107  i: [FFmpeg] [INFO] 

04-08 16:13:04.107  i: [FFmpeg] [INFO] [FFmpegExtractor] Created filter for h264.
04-08 16:13:04.108  i: [FFmpeg] [INFO] [FFmpegExtractor] Created filter for aac.
04-08 16:13:04.108  i: [FFmpeg] [INFO] [FFmpegExtractor] Requesting IO seek to 0 bytes.
04-08 16:13:04.108  i: [FFmpeg] [INFO] [FFmpegExtractor] IO seek completed to -38 Interrupted: No Closed: No
04-08 16:13:04.108  i: [FFmpeg] [INFO] [FFmpegExtractor] Requesting IO seek to -1 bytes.
04-08 16:13:04.108  i: [FFmpegExtractor] IO-seek has been requested, target of -1 bytes (whence 2).
04-08 16:13:04.109  i: [FFmpegExtractor] IO-seek not resolvable, returning -38 instead.
04-08 16:13:04.109  w: [FF] AVC configuration parser failed, falling back to using the original initialisation data.
04-08 16:13:04.109  i: [VideoStream] Dolby Vision is unsupported on this display or device.
04-08 16:13:04.109  i: [FFmpegExtractor] Container: Container[mpegts] No Title - 0 kbps, -54 seconds [CT: 0us, ST: 24726622us, SRT: -9223372036854775808us]..
04-08 16:13:04.110  i: [FFmpegExtractor] Track found: VideoStream[0-h264] 1280x720 [SAR 1:1, DAR 16:9]. H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 - Unknown Profile (video/avc), ~-96 kbps -54 seconds 59.94fps, No Title / Unknown (null), 1 / 49 bytes, ..
04-08 16:13:04.114  i: [FFmpeg] [INFO] [FFmpegExtractor] IO seek completed to -38 Interrupted: No Closed: No
04-08 16:13:04.115  i: [FFmpegExtractor] Track found: AudioStream[1-aac] 0 channels over 0 (null), 24000 Hz, 0,0 padding. AAC (Advanced Audio Coding) - Unknown Profile (audio/mp4a-latm), 96 kbps -54 seconds 0.00fps, No Title / Unknown (null), 1 / 2 bytes, ..
04-08 16:13:04.116  i: [ExoPlayer][EventLogger] videoInputFormat [eventTime=9.07, mediaPos=14.78, window=0, period=0, id=0, mimeType=video/avc, codecs=h264, res=1280x720, fps=59.94006]
04-08 16:13:04.139  i: [ExoPlayer][EventLogger] audioDecoderInitialized [eventTime=9.09, mediaPos=14.78, window=0, period=0, c2.android.aac.decoder]
04-08 16:13:04.140  i: [ExoPlayer][EventLogger] audioInputFormat [eventTime=9.09, mediaPos=14.78, window=0, period=0, id=1, mimeType=audio/mp4a-latm, bitrate=96082, codecs=aac, channels=0, sample_rate=24000, language=unknown, selectionFlags=[default,forced]]
04-08 16:13:04.140  i: [TranscodeSession] Updating session status
04-08 16:13:04.141  i: [TranscodeSession] Direct Play
04-08 16:13:04.159  i: [ExoPlayer][EventLogger] videoDisabled [eventTime=9.11, mediaPos=14.78, window=0, period=0]
04-08 16:13:04.161  i: [ExoPlayer][EventLogger] audioDisabled [eventTime=9.11, mediaPos=14.78, window=0, period=0]
04-08 16:13:04.168  i: [FFmpegExtractor] Interrupting extractor for release.
04-08 16:13:04.170  i: [FFmpeg] [INFO] [FFmpegExtractor] Closing demuxer context.
04-08 16:13:04.170  i: [FFmpeg] [INFO] [FFmpegExtractor] Source has been closed successfully.
04-08 16:13:04.170  i: [FFmpegExtractor] Extractor has been released.
04-08 16:13:04.171  i: [LoadControl] Setting buffer size to 73.19 MB / 0 seconds.
04-08 16:13:04.172  e: [ExoPlayer][EventLogger] playerFailed [eventTime=9.12, mediaPos=14.78, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
  com.google.android.exoplayer2.r: MediaCodecAudioRenderer error, index=3, format=Format(1, null, null, audio/mp4a-latm, aac, 96082, unknown, [-1, -1, -1.0], [0, 24000]), format_supported=YES
      at com.google.android.exoplayer2.x1.handleMessage(SourceFile:357)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:226)
      at android.os.Looper.loop(Looper.java:313)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: y3.m: Decoder failed: c2.android.aac.decoder
      at y3.o.m(Unknown Source:2)
      at y3.o.render(SourceFile:154)
      at com.google.android.exoplayer2.x1.p(SourceFile:97)
      at com.google.android.exoplayer2.x1.handleMessage(SourceFile:221)
      ... 4 more
  Caused by: android.media.MediaCodec$CodecException: Error 0xe
]
04-08 16:13:04.173  e: [Player][ExoPlayer] Playback error detected
04-08 16:13:04.174  i: [Player][Timeline] Handling player error
04-08 16:13:04.174  i: [Player][Timeline] Playback stopped (error: true)
04-08 16:13:04.175  e: An exception occurred: com.google.android.exoplayer2.r: MediaCodecAudioRenderer error, index=3, format=Format(1, null, null, audio/mp4a-latm, aac, 96082, unknown, [-1, -1, -1.0], [0, 24000]), format_supported=YES
04-08 16:13:04.175  e: Stacktrace: com.google.android.exoplayer2.r: MediaCodecAudioRenderer error, index=3, format=Format(1, null, null, audio/mp4a-latm, aac, 96082, unknown, [-1, -1, -1.0], [0, 24000]), format_supported=YES
	at com.google.android.exoplayer2.x1.handleMessage(SourceFile:357)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: y3.m: Decoder failed: c2.android.aac.decoder
	at y3.o.m(Unknown Source:2)
	at y3.o.render(SourceFile:154)
	at com.google.android.exoplayer2.x1.p(SourceFile:97)
	at com.google.android.exoplayer2.x1.handleMessage(SourceFile:221)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xe
```

**Comment by Fyb3roptik** [comment]
What is set in ffmpeg settings on threadfin? That's odd that it's not finding audio channels.

**Comment by mkanet** [comment]
FFMpeg flags:                      **-hide_banner -loglevel error -i [URL] -c copy -f mpegts pipe:1**

Buffer Size:                          ```.5MB```
Timeout for new client:       ```500ms```
FFmpeg Binary Path:           ```C:\Program Files (x86)\IPTV\ffmpeg.exe```
ffmpeg version:                   ```2023-04-06-git-b564ad8eac-full_build-www.gyan.dev```

Is this something that can be prevented with appropriate ffmpeg flags?

**Comment by mkanet** [comment]
@Fyb3roptik I am happy to say I finally figured out the issue!  

All the weird audio decoding errors I found in the Plex mobile client debug log is because the aac streams provided by my provider are not fully compatible with Plex.  Provider's native aac format isn't encoded very well.  I had to use ffmpeg in threadfin to reencode the aac to a more standard format:   Below are the flags I'm using to fix this issue:
```
-hide_banner -loglevel error -i [URL] -c:a aac -c:v copy -f mpegts pipe:1
```

I can also re-encode to mp3 as suggested by xteve FAQ's:
![Screenshot 04-09-2023 at 10 07 40 AM](https://user-images.githubusercontent.com/811008/230786415-756c87a2-6b3a-4ce9-a116-d1daf7c8bf7c.png)

**Comment by Fyb3roptik** [comment]
AAC is standard so stick with that. Yeah that's a good snag! Have you tried using cuda? Do you have an Nvidia card?

**Comment by mkanet** [comment]
> AAC is standard so stick with that. Yeah that's a good snag! Have you tried using cuda? Do you have an Nvidia card?

The provider already has AAC, however the AAC encoder they used isn't very compatible with some plex clients.  If I use MP3, Plex will tune into the channel even faster on Plex.  

I don't have nvidia  GPU.  I have a very powerful Intel i7 137000k UHD770 IGPU for video encoding (QuickSync) which has much more processing power.
